### ISSUE TITLE
where is my book

### ISSUE THREAD

**Issue by damlaYasarr** [thecoderverse/MiniVerse#31]
Merhabalar, whereisbook adındaki projeyi yapmak istiyorum. projeyi fork ettim ama mümkün mü yapmam?

**Comment by muhtalipdede** [comment]
Merhaba @damlaYasarr,

Tabi ki fork üzerinde geliştirme yapıp sonrasında pull request oluşturabilirsin.

Aynı konu için "wimb" klasörü üzerinde @buraksenyurt hocamın rust diliyle yazmış olduğu bir örnek de var. Belki yönlendirici olur senin için. Oluşturacağın yeni projeyi "wimb-2" gibi isimlendirirsen çok seviniriz.

Şimdiden eline sağlık.

Sevgiler.

**Comment by damlaYasarr** [comment]
çok teşekkür ederim:) peki bir sorum daha var, python ile yazmayı planlıyorum ama belirlediğiniz dil var mı?

**Comment by muhtalipdede** [comment]
Bu konuda özgürsün, istediğin programlama diliyle yazabilirsin.
