### ISSUE TITLE
MyDay:

### ISSUE THREAD

**Issue by damlaYasarr** [thecoderverse/MiniVerse#34]
MyDay, Bunu da yapmayı planlıyorum. Tavsiye edeceğiniz dil var mı python qt5 kütüphanesi ile mi veya elektronjs'le  mi yapmak gerekir

**Comment by muhtalipdede** [comment]
Selamlar Damla,

İstediğin dil yada framework kullanabilirsin. İkisi de uygundur bizim için. 

Sevgiler,
Muhtalip
